/* ================= OWNER CONFIGURATION =================
   Insert your own restricted, low-quota keys below. These keys are visible
   to anyone who can view this static GitHub Pages site; never use secret keys.
   Visitors are never shown an API-key settings screen. */
const API_KEYS = { openai: "PUT_OPENAI_KEY_HERE", gemini: "PUT_GEMINI_KEY_HERE", anthropic: "PUT_ANTHROPIC_KEY_HERE" };

const PROVIDERS = {
  openai: { name: "OpenAI", models: ["gpt-4o-mini", "gpt-4o"] },
  gemini: { name: "Google Gemini", models: ["gemini-2.0-flash", "gemini-1.5-pro"] },
  anthropic: { name: "Anthropic", models: ["claude-3-5-haiku-latest", "claude-3-5-sonnet-latest"] }
};
const STORAGE_KEY = "ai-hub-conversations-v1", SETTINGS_KEY = "ai-hub-settings-v1";
let conversations = load(STORAGE_KEY, []), settings = load(SETTINGS_KEY, { provider: "openai", model: "gpt-4o-mini", theme: "dark" });
let activeId = null, controller = null, retryMessage = null;
const $ = (s) => document.querySelector(s);
const els = { list: $("#conversationList"), title: $("#conversationTitle"), provider: $("#providerSelect"), model: $("#modelSelect"), messages: $("#messages"), empty: $("#emptyState"), input: $("#messageInput"), send: $("#sendButton"), scroll: $("#chatScroll"), bar: $("#generationBar"), genText: $("#generationText"), sidebar: $("#sidebar"), backdrop: $("#sidebarBackdrop") };
function load(key, fallback) { try { return JSON.parse(localStorage.getItem(key)) || fallback; } catch { return fallback; } }
function save() { localStorage.setItem(STORAGE_KEY, JSON.stringify(conversations)); localStorage.setItem(SETTINGS_KEY, JSON.stringify(settings)); }
function escapeHtml(value) { return String(value).replace(/[&<>"]/g, c => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;" })[c]); }
function markdown(text) { let html = escapeHtml(text); html = html.replace(/```([\s\S]*?)```/g, (_, code) => `<pre><code>${code.trim()}</code><button class="copy-code">Copy</button></pre>`); html = html.replace(/`([^`]+)`/g, "<code>$1</code>").replace(/^### (.*)$/gm,"<h3>$1</h3>").replace(/^## (.*)$/gm,"<h2>$1</h2>").replace(/^# (.*)$/gm,"<h1>$1</h1>").replace(/\*\*(.*?)\*\*/g,"<strong>$1</strong>").replace(/\*(.*?)\*/g,"<em>$1</em>").replace(/^[-*] (.*)$/gm,"<li>$1</li>").replace(/(<li>[\s\S]*?<\/li>)/g,"<ul>$1</ul>").replace(/\n\n/g,"</p><p>").replace(/\n/g,"<br>"); return `<p>${html}</p>`; }
function active() { return conversations.find(c => c.id === activeId); }
function makeConversation() { const c = { id: crypto.randomUUID(), title: "New conversation", createdAt: Date.now(), updatedAt: Date.now(), provider: settings.provider, model: settings.model, messages: [] }; conversations.unshift(c); activeId = c.id; save(); return c; }
function fillProviders(select, selected) { select.innerHTML = Object.entries(PROVIDERS).map(([id,p]) => `<option value="${id}" ${id===selected?"selected":""}>${p.name}</option>`).join(""); }
function fillModels(select, provider, selected) { select.innerHTML = PROVIDERS[provider].models.map(m => `<option value="${m}" ${m===selected?"selected":""}>${m}</option>`).join(""); }
function groupFor(date) { const day = 864e5, d = new Date(date), today = new Date(); today.setHours(0,0,0,0); const diff = Math.floor((today - new Date(d).setHours(0,0,0,0))/day); return diff===0?"Today":diff===1?"Yesterday":diff<7?"Previous 7 Days":"Older"; }
function renderList(filter = "") { const groups = { Today:[], Yesterday:[], "Previous 7 Days":[], Older:[] }; conversations.filter(c => c.title.toLowerCase().includes(filter.toLowerCase())).sort((a,b)=>b.updatedAt-a.updatedAt).forEach(c=>groups[groupFor(c.updatedAt)].push(c)); els.list.innerHTML = Object.entries(groups).map(([name,items]) => !items.length ? "" : `<div class="conversation-group"><div class="group-label">${name}</div>${items.map(c=>`<button class="conversation-item ${c.id===activeId?"active":""}" data-id="${c.id}"><span class="name">${escapeHtml(c.title)}</span><span class="more" title="Rename">•••</span></button>`).join("")}</div>`).join("") || `<p class="group-label">No conversations found</p>`; }
function renderChat() { const c = active(); if (!c) { els.title.textContent="New conversation"; els.messages.innerHTML=""; els.empty.hidden=false; fillProviders(els.provider,settings.provider); fillModels(els.model,settings.provider,settings.model); return; } els.title.textContent=c.title; fillProviders(els.provider,c.provider); fillModels(els.model,c.provider,c.model); els.empty.hidden=!!c.messages.length; els.messages.innerHTML=c.messages.map((m,i)=>`<article class="message ${m.role}"><div class="avatar">${m.role==="user"?"You":"✦"}</div><div class="message-body"><div class="message-meta">${m.role==="user"?"You":"AI Hub"}</div><div class="message-content">${markdown(m.content)}</div>${m.error?`<div class="error-card">${escapeHtml(m.error)}<br><button class="retry-button" data-retry="${i}">Retry response</button></div>`:""}</div></article>`).join(""); requestAnimationFrame(()=>els.scroll.scrollTop=els.scroll.scrollHeight); }
function updateComposer() { els.input.style.height="auto"; els.input.style.height=Math.min(els.input.scrollHeight,170)+"px"; els.send.disabled=!els.input.value.trim()||!!controller; }
function changeModel() { const c=active() || makeConversation(); c.provider=els.provider.value; c.model=els.model.value; c.updatedAt=Date.now(); save(); renderList(); }
function requestConfigured(provider) { const key=API_KEYS[provider]; return key && !key.startsWith("PUT_"); }
async function callProvider(c) { const key=API_KEYS[c.provider], signal=controller.signal; if (!requestConfigured(c.provider)) throw new Error(`The ${PROVIDERS[c.provider].name} key has not been configured by this site's owner.`); const history=c.messages.filter(m=>!m.error).map(m=>({role:m.role,content:m.content})); let response, data;
  if(c.provider==="openai"){ response=await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${key}`},body:JSON.stringify({model:c.model,messages:history.map(m=>({role:m.role,content:m.content}))}),signal}); data=await response.json(); if(!response.ok) throw new Error(data.error?.message||"OpenAI request failed."); return data.choices?.[0]?.message?.content; }
  if(c.provider==="gemini"){ const contents=history.map(m=>({role:m.role==="assistant"?"model":"user",parts:[{text:m.content}]})); response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${c.model}:generateContent?key=${encodeURIComponent(key)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contents}),signal}); data=await response.json(); if(!response.ok) throw new Error(data.error?.message||"Gemini request failed."); return data.candidates?.[0]?.content?.parts?.map(p=>p.text).join(""); }
  response=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"Content-Type":"application/json","x-api-key":key,"anthropic-version":"2023-06-01"},body:JSON.stringify({model:c.model,max_tokens:2048,messages:history.map(m=>({role:m.role,content:m.content}))}),signal}); data=await response.json(); if(!response.ok) throw new Error(data.error?.message||"Anthropic request failed."); return data.content?.map(p=>p.text||"").join("");
}
async function sendMessage(text, retry=false) { const c=active() || makeConversation(); if(!retry){ c.messages.push({role:"user",content:text}); if(c.title==="New conversation") c.title=text.replace(/\s+/g," ").slice(0,52); } else { c.messages.pop(); } c.updatedAt=Date.now(); save(); renderList(); renderChat(); els.input.value=""; updateComposer(); controller=new AbortController(); els.bar.hidden=false; els.genText.textContent=`${PROVIDERS[c.provider].name} is thinking…`; try { const answer=await callProvider(c); if(!answer) throw new Error("The provider returned an empty response."); c.messages.push({role:"assistant",content:answer}); } catch(error) { if(error.name!=="AbortError") c.messages.push({role:"assistant",content:"",error:error.message||"Unable to complete this request."}); } finally { controller=null; c.updatedAt=Date.now(); save(); els.bar.hidden=true; renderList(); renderChat(); updateComposer(); } }
function openConversation(id){activeId=id; renderList($("#searchInput").value);renderChat();els.sidebar.classList.remove("open");els.backdrop.classList.remove("open");}
$("#newChatButton").onclick=()=>{activeId=null;renderList();renderChat();els.input.focus();}; els.list.onclick=e=>{const b=e.target.closest("[data-id]");if(!b)return;if(e.target.classList.contains("more")){openRename(b.dataset.id);return;}openConversation(b.dataset.id);}; $("#searchInput").oninput=e=>renderList(e.target.value); $("#composer").onsubmit=e=>{e.preventDefault();if(els.input.value.trim()&&!controller)sendMessage(els.input.value.trim());}; els.input.oninput=updateComposer; els.input.onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();$("#composer").requestSubmit();}}; els.provider.onchange=()=>{fillModels(els.model,els.provider.value,PROVIDERS[els.provider.value].models[0]);changeModel();};els.model.onchange=changeModel; $("#stopButton").onclick=()=>controller?.abort(); $("#messages").onclick=e=>{if(e.target.classList.contains("copy-code")){navigator.clipboard.writeText(e.target.previousElementSibling.textContent);e.target.textContent="Copied";setTimeout(()=>e.target.textContent="Copy",1200);}if(e.target.classList.contains("retry-button")){const c=active(), i=Number(e.target.dataset.retry);retryMessage=c.messages[i-1]?.content;if(retryMessage)sendMessage(retryMessage,true);}};document.querySelectorAll("[data-prompt]").forEach(b=>b.onclick=()=>{els.input.value=b.dataset.prompt;updateComposer();els.input.focus();});
const settingsDialog=$("#settingsDialog"); $("#settingsButton").onclick=()=>{fillProviders($("#defaultProvider"),settings.provider);fillModels($("#defaultModel"),settings.provider,settings.model);$("#themeSelect").value=settings.theme;settingsDialog.showModal();};$("#defaultProvider").onchange=e=>fillModels($("#defaultModel"),e.target.value,PROVIDERS[e.target.value].models[0]);$("#themeSelect").onchange=e=>{settings.theme=e.target.value;document.body.dataset.theme=e.target.value;save();};settingsDialog.addEventListener("close",()=>{settings.provider=$("#defaultProvider").value;settings.model=$("#defaultModel").value;save();});$("#clearChatsButton").onclick=()=>{if(confirm("Delete every saved conversation? This cannot be undone.")){conversations=[];activeId=null;save();settingsDialog.close();renderList();renderChat();}};
const renameDialog=$("#renameDialog"); function openRename(id){activeId=id;$("#renameInput").value=active().title;renameDialog.showModal();setTimeout(()=>$("#renameInput").select(),0);}$("#renameButton").onclick=()=>active()&&openRename(activeId);$("#saveRenameButton").onclick=()=>{const c=active(),name=$("#renameInput").value.trim();if(c&&name){c.title=name;c.updatedAt=Date.now();save();renderList();renderChat();}}; $("#menuButton").onclick=()=>{els.sidebar.classList.add("open");els.backdrop.classList.add("open");};els.backdrop.onclick=()=>{els.sidebar.classList.remove("open");els.backdrop.classList.remove("open");};document.addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();$("#newChatButton").click();}});
document.body.dataset.theme=settings.theme; renderList();renderChat();updateComposer();
